# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abhinandan Das
title: Data Scientist
email: abhinandandas658@gmail.com
website: https://abhinandan305.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: abhinandan_in_uk
linkedin_username: Abhinandan Das
# xing_username: jekyll
# pinterest_username: jekyll

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abhinandan Das
title: Data Scientist
email: abhinandandas658@gmail.com
website: https://abhinandan305.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username: sproogen
instagram_username: abhinandan_in_uk
linkedin_username: Abhinandan Das

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  **About Me**  

  Welcome! I am Abhinandan Das, a Master's student in Data Science (Business and Management) at the University of Manchester, driven by a passion for transforming data into actionable insights. With a Global Futures Scholarship and a strong academic foundation, my expertise spans Python for Business Analytics, Text Mining, and Statistics and Machine Learning. My dissertation focuses on Sequence Mining and Aspect Detection using NLP on Airbnb reviews.  

  I bring two years of professional experience as a Business Analyst at LTIMindtree, where I worked with ABSA to deliver impactful results in financial data analysis, application support, and strategic decision-making. I excelled in designing reports and dashboards, conducting root cause analyses, and maintaining exceptional client satisfaction. My work emphasized efficiency and operational excellence, supported by tools like Power BI, Tableau, and SQL.  

  In addition, I recently completed a Data Scientist internship at ITV, where I predicted audience engagement for new series using machine learning models, achieving a top accuracy of 83%.  

  Beyond academics and work, I am passionate about solving complex problems through data storytelling and cutting-edge analytics. My technical proficiencies include Python, SQL, MongoDB, and Power BI, complemented by a strong analytical mindset, adaptability, and collaboration skills.  

  Let’s connect and explore how data can drive innovation!

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Sequence Mining & Aspect Detection Using NLP
        link: github.com/Abhinandan305/sequence-mining
        additional_links:
          - title: View Project on GitHub
            icon: fab fa-github
            url: https://github.com/Abhinandan305/sequence-mining
        description: |
          Analyzed sentiment trends in Airbnb reviews using Natural Language Processing (NLP). Developed sequence mining and aspect detection algorithms to identify key areas for service improvement for Airbnb hosts.

      - layout: top-middle
        title: Time Series Analysis and Forecasting
        link: github.com/Abhinandan305/time-series-forecasting
        additional_links:
          - title: View Project on GitHub
            icon: fab fa-github
            url: https://github.com/Abhinandan305/time-series-forecasting
        description: |
          Built a Time Series Sales Forecasting model using historical data with ~90% accuracy. Applied Machine Learning models such as Random Forest and XGBoost Regression using Python.

      - layout: top-middle
        title: Ecommerce Database System Design
        link: github.com/Abhinandan305/ecommerce-database
        additional_links:
          - title: View Project on GitHub
            icon: fab fa-github
            url: https://github.com/Abhinandan305/ecommerce-database
        description: |
          Designed a NoSQL database system for an e-commerce platform, optimizing queries and visualizing stock management. Added features like same-day delivery and reduced product wastage.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Data Scientist Intern
        link: itv.com
        sub_title: ITV, Manchester, UK
        caption: January 2024 - February 2024
        description: |
          - Predicted user engagement for the series "Spy Among Friends" using machine learning models.
          - Achieved 83% accuracy with Logistic Regression and optimized performance using precision, recall, and F1-score metrics.
          - Tech stack: Python, Statistical Analysis, Predictive Analytics.

      - layout: left
        title: Business Analyst
        link: ltimindtree.com
        sub_title: LTIMindtree, Kolkata, India
        caption: August 2021 - August 2023
        description: |
          - Delivered financial data insights through reports and dashboards for ABSA, a leading South African bank.
          - Managed L2 & L3 application support, ensuring SLA compliance and system optimization.
          - Conducted root cause analyses, acceptance testing, and health checks, maintaining a 4.9/5 Client Satisfaction Rating.
          - Tech stack: ServiceNow, Power BI, Tableau, Oracle SQL, Python.

  - title: Education
    layout: list
    content:
      - layout: left
        title: MSc Data Science (Business and Management)
        sub_title: University of Manchester
        caption: 2023 - 2024
        description: |
          - Modules: Python for Business Analytics, Text Mining (NLP), Statistics and Machine Learning, Data Ethics.
          - Dissertation: Sequence Mining & Aspect Detection Using NLP on Airbnb Reviews.
          - Awarded the Global Futures Scholarship.

      - layout: left
        title: Bachelor of Computer Applications
        sub_title: IEM, Kolkata
        caption: 2018 - 2021
        description: |
          - Modules: Numerical Analysis, Java, C, C++, DBMS, Python, Digital Electronics.
          - Graduated with a CGPA of 9.37.

  - title: A Little More About Me
    layout: text
    content: | 
      Outside of academics and work, my interests and hobbies include:
      - Fitness and Hiking
      - Photography
      - Premier League Football
      - Exploring data science trends and innovations.


      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
